env:
  global:
   # Encrypted COVERITY_SCAN_TOKEN
   - secure: "a0E5j3yZsziPmAiF8BLgvZ55v56hgE/JtEKPBc5LkibbsAqslU0wX6mf5p9yKQ0DoWowbs/4AV361rgjKBa/+8Y1zVhlj4FqpSrUHUd8rq9HYmlowB95Hpxr4NUW+Echt+IiNQ+l+NHMbtOgU5EnZ3hjtOFvnsB4SG7PJ8gKM7RUJcu0V/HNkmZfEJz19PF0k4lJcFX25cp95jKuwoUapRVMT3ijnpoBn/ttYaJhKMqrEGemtvh0sMWUKZHjr9pIf/pDbH7ZsRCUq/Clw88Fqds4NyfbOSw7mlD99ZkVRva9tpXBPqg5JYUxa3dImEeXNovHFLn73U3wi1bshwfwp7KcgZjgBXmMLYXGKDATnm9lZZoNUYTPTp7Ug9dUJpFt2oo9btcVfJC6htj+MktFsLPVfp+h89Zmv6BYQXpeYHgx3SVhCB54uBBkQ/ifFaRnymVyE+lEcEceUCxeVp4gYlSgCUTVvdfT32NUKfiitfmXA/gda+tK6LecKrEWTE05b7Kox/Co242PIobYgDNUgyLSewWCgsNf3LkVX/9Dk1RkCCcmJg3uyyu//0VOLZYGxz9yPtNSCVXKFVyoQ9shYOprMd3eDrkD3OaSpuXEbOBbsUJ7taZcNv2eWVktUyJDr2TC63d6exhSxrJowCXpjFrIEYMsyfHXirZ6Ly4DNkA="

language: cpp
matrix:
    include:
        - name: "GCC (7.4) on Ubuntu 18.04"
          os: linux
          dist: bionic
          compiler: gcc
          addons:
              coverity_scan:
                  project:
                      name: "dominikschnitzer/musly"
                      description: "Musly"
                  notification_email: dominik@schnitzer.at
                  build_command_prepend: "mkdir -p build; cd build; cmake -DBUILD_STATIC=ON -DCMAKE_BUILD_TYPE=Release ${CARGS} .."
                  build_command: "cmake --build . --config Release"
                  branch_pattern: coverity-scan
              apt:
                  packages:
                      - libeigen3-dev
                      - libavcodec-dev
                      - libavformat-dev
                      - libavutil-dev

        - name: "GCC (5.4) on Ubuntu 16.04"
          os: linux
          dist: xenial
          compiler: gcc

        - name: "Clang (7.0) on Ubuntu 18.04"
          os: linux
          dist: bionic
          compiler: clang

        - name: "MSVC (19.16) on VS 2017/Windows 1809"
          os: windows
          before_install:
              - curl -O https://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-4.2-win64-dev.zip
              - unzip ffmpeg-4.2-win64-dev.zip
              - curl -O https://bitbucket.org/eigen/eigen/get/3.3.7.zip
              - unzip 3.3.7.zip
              - export CARGS="-DCMAKE_GENERATOR_PLATFORM=x64 -DEIGEN3_INCLUDE_DIR=$(pwd)/eigen-eigen-323c052e1731 -DLIBAV_ROOT_DIR=$(pwd)/ffmpeg-4.2-win64-dev"

        - name: "AppleClang (11.0) on XCode 11/OSX 10.14"
          os: osx
          osx_image: xcode11


script:
    - mkdir -p build
    - cd build
    - cmake -DBUILD_STATIC=ON -DCMAKE_BUILD_TYPE=Release ${CARGS} ..
    - cmake --build . --config Release

addons:
    apt:
        packages:
            - libeigen3-dev
            - libavcodec-dev
            - libavformat-dev
            - libavutil-dev
    homebrew:
        packages:
            - ffmpeg
            - eigen
